### ISSUE TITLE
Adding Cells

### ISSUE THREAD

**Issue by Chongsyl** [tianchengzhe/EllipTrack#1]
Would it be possible to add a function that adds missed/new cells to the segmentation and training?

Thank you

**Comment by tianchengzhe** [comment]
This should be possible. Can you describe how you would like to add cells? e.g., via a manual tool?

**Comment by Chongsyl** [comment]
Yes, a manual drag tool for ellipses (for nuclear tracking) and a free draw tool.

Thank you!

**Comment by tianchengzhe** [comment]
Sure, I can do that. However, writing a new GUI and its associated documentation will take quite some time, and I am very occupied right now. It might take a few weeks. Also, if you don't mind, may I ask you to help me to design the GUI to make it user-friendly?

**Comment by Chongsyl** [comment]
Yes, absolutely.

**Comment by tianchengzhe** [comment]
Solved via email. Beta testing now. Will publish the new GUI after finalization.
