### ISSUE TITLE
The URL in the readme cannot be accessed

### ISSUE THREAD

**Issue by lzhzju** [tianchengzhe/EllipTrack#3]
https://biof-git.colorado.edu/biofrontiers-imaging/bioformats-image-toolbox/wikis/home
May I ask why can't I open this link……

**Comment by tianchengzhe** [comment]
The University of Colorado seems to introduce a new firewall policy preventing users outside of the university to access the git-lab page. But I have attached a version of BioformatsImage in the following folder. Please install it (as a Matlab toolbox).

https://github.com/tianchengzhe/EllipTrack/tree/master/third_party_functions

**Comment by zjulzhhh** [comment]
thank you!

**Comment by lzhzju** [comment]
It works, Thank you very much!
